version: '3'
services:

   mongodb:
      image: mongo:latest
      restart: on-failure
      volumes:
        - $HOME/Documents/udaanDb:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017


